### ISSUE TITLE
Following test fails

### ISSUE THREAD

**Issue by v3ss0n** [doppio/word2num#2]
I am trying a few test and following fails
```py
    ("zero five zero four 2002", "05042002"), ## None TYpe
    ("nineteen seventy-six", "1976"), ##  '95'   ?? why?

````

**Comment by doppio** [comment]
Hi @v3ss0n ,

Thanks for opening the issue and for checking out the package.

> ("zero five zero four 2002", "05042002"), ## None TYpe

`word2num` is more about getting numbers from **natural language** rather than piecing together mixed formats, so it doesn't recognize "2002." However, it _can_ make sense of `zero five zero four two thousand and two`, which it evaluates as `5042002`. Note that since the package's goal is to interpret natural language as **numerical** amounts, the leading "zero" is not expressed in the return value.


> ("nineteen seventy-six", "1976"), ##  '95'   ?? why?

In cases like this, the parser adds up the values within the expression. For example, "fifty-six" gets parsed as 50 + 6. In your example, something similar is happening: 19 + 70 + 6 = 95.

The original intent of this package was simply to interpret numbers written out in words like "five thousand and seventy-six." I added support for "digit sequences" in order to parse decimal values like "seventy-five point **one four five**". I can see how that would lead you to expect the package to parse more generic number sequences like "nineteen seventy-six." I'd consider adding support for this and would welcome a pull request if that's something a contributor would like to see added to the package. 🙂
